export const keywords = [
  "HTML5",
  "CSS3",
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Vue.js",
  "Redux",
  "Zustand",
  "Tailwind CSS",
  "SASS",
  "Styled Components",
  "Framer Motion",
  "Webpack",
  "Vite",
  "Babel",
  "ESLint",
  "Prettier",
  "Figma",
  "Adobe XD",
  "Storybook",
  "Context API",
  "Redux Toolkit",
  "Recoil",
  "Jest",
  "React Testing Library",
  "Cypress",
  "Playwright",
  "Node.js",
  "Express.js",
  "Prisma",
  "GraphQL",
  "REST API",
  "Netlify",
  "Vercel",
  "Firebase",
  "AWS",
  "Docker",
  "Agile",
  "Scrum",
  "CI/CD",
  "Git",
  "Responsive Design",
  "Accessibility (A11y)",
  "SEO",
  "Performance Optimization",
  "Toronto",
  "Montreal",
  "Vancouver",
  "Ottawa",
  "Remote Canada",
  "Bilingual (English/French)",
  "Work Permit",
  "Open to Relocation in Canada",
  "Canadian Experience",
  "Tech Startup Canada",
  "Front-End Developer",
  "UI Developer",
  "React Developer",
  "Web Developer",
  "Software Engineer Front-End",
  "Collaborative",
  "Problem Solver",
  "Detail-Oriented",
];
